### ISSUE TITLE
Can I perform high-level control of the A1 robot from Gazebo?

### ISSUE THREAD

**Issue by RML-Mechaking** [unitreerobotics/unitree_ros#101]
Can I perform high-level control of the A1 robot from Gazebo? 
If so, could you tell me how to do it? 
If not, why can't it be done?

**Comment by xiaoliangstd** [comment]
Hello, the A1 robot cannot use the high-level interface in Gazebo because our locomotion control program does not use ROS.

**Comment by RML-Mechaking** [comment]
Could you let me know how to use velocity and torque control in the low-level control of A1 in Gazebo?

**Comment by xiaoliangstd** [comment]
You could reference this repo: https://github.com/unitreerobotics/unitree_guide
