### ISSUE TITLE
Need Base Velocity of Unitree Go2 for Policy Observations

### ISSUE THREAD

**Issue by BibsCode** [unitreerobotics/unitree_ros#103]
We are working with a policy that requires the base velocity of the Unitree Go2, which is part of the observations. 
The base velocity is published by the sports mode on ROS, but we need to deactivate the sports service because we want to send low-level commands.

**Problem**:
- We need the base velocity for our policy observations.
- The base velocity is currently published by the sports mode on ROS.
- We need to deactivate the sports service to send low-level commands, which stops the publication of the base velocity.

**Questions**:
- Is there an alternative way to calculate the base velocity using a formula or algorithm?
- Is it possible to configure the system so that the sports topic continues to be published even when the sports service is deactivated?
- How is the base velocity internally calculated or determined by the Unitree Go2? Understanding this might help us replicate the calculation when the sports service is off.

Thank you!

**Comment by Jdowdy05** [comment]
@BibsCode did you find a solution for this?
