### ISSUE TITLE
hardware_interface issue in simulation

### ISSUE THREAD

**Issue by ramil115** [unitreerobotics/unitree_ros#15]
After successfull building I got the following problem when running simulation in Gazebo:

gzserver: /opt/ros/melodic/include/hardware_interface/joint_command_interface.h:60: void hardware_interface::JointHandle::setCommand(double): Assertion `cmd_' failed.
Aborted (core dumped)

**Comment by Zhaiweiwei0** [comment]
Sorry, we haven't come across this problem, Maybe there has some wrong with your ROS package.

**Comment by TrivasZhang** [comment]
Feel free to reopen it if needed.
