### ISSUE TITLE
More detailed examples about how to use the "joint_controller.cpp" in "unitree_legged_control" folder

### ISSUE THREAD

**Issue by edward9503** [unitreerobotics/unitree_ros#18]
Hi there,

I saw in the unitree_ros github description, it says that the "joint_controller.cpp" in folder "unitree_legged_control" contains the joints controllers for simulation, where we can control joints with position, velocity and torque. But the detailed examples about how to use it are lacking. So I was wondering if there are some tutorials about this controller. 

Thanks a lot!

**Comment by Zhaiweiwei0** [comment]
Sorry, the simulation cannot do high-level control, we've explained this in the introduction section of the README.md file.

**Comment by chitianqilin** [comment]
That will be very useful if Unitree can provide a high-level example running in Gazebo simulation.
