### ISSUE TITLE
Complete Sensors URDF - AlienGo

### ISSUE THREAD

**Issue by itaouil** [unitreerobotics/unitree_ros#26]
Hi,

We have an AlienGo robot equipped with two D435 cameras and a T265.

Is there available somewhere the URDF model with the correct transformations (i.e imu to upper D435 camera transformation).

Or a way to start the publishing of the tf tree on the robot?

Or would I have to measure it myself?

Best,
Ilyass

**Comment by itaouil** [comment]
Any update on this? @Unitree @TrivasZhang @Zhaiweiwei0

**Comment by TrivasZhang** [comment]
Please leave me your email

**Comment by itaouil** [comment]
Hi,

Here is my university email:

s6iltaou@uni-bonn.de

**Comment by itaouil** [comment]
Hi @TrivasZhang,

In order to publish the TF tree of the robot I would have to need access to the joint states information of the robot (i.e. the motor state information).

But there is a problem. I can only access those info if I am in low level mode, which is not convenient.

Unfortunately, without the motor info I cannot publish the tf frame....

Is there a way to add motor state information to the high state info? Or run both high level and low level connections at the same time?
