### ISSUE TITLE
TF tree AlienGo

### ISSUE THREAD

**Issue by itaouil** [unitreerobotics/unitree_ros#29]
Hi @TrivasZhang @Zhaiweiwei0 @ZKBian,

In order to publish the TF tree of the robot I would have to need access to the joint states information of the robot (i.e. the motor state information).

But there is a problem. I can only access those info if I am in low level mode, which is not convenient.

Unfortunately, without the motor info I cannot publish the tf frame....

Is there a way to add motor state information to the high state info? Or run both high level and low level connections at the same time?

**Comment by TrivasZhang** [comment]
#27

**Comment by itaouil** [comment]
Ok.

Let us keep the discussion on the other issue :).
