### ISSUE TITLE
GO1 SDK 

### ISSUE THREAD

**Issue by JonathanMortes** [unitreerobotics/unitree_ros#30]
Hi, 

When will the GO1's SDK (in all it's configs) be uploaded to the main repo?

Thanks

**Comment by TrivasZhang** [comment]
https://github.com/unitreerobotics/unitree_legged_sdk/releases/tag/3.4.2

**Comment by TrivasZhang** [comment]
Remember to upgrade the sport mode. Ask sales team for support.

**Comment by JonathanMortes** [comment]
Thanks!
