### ISSUE TITLE
ROS Noetic Error: cannot find -lunitree_legged_sdk

### ISSUE THREAD

**Issue by dbaldwin** [unitreerobotics/unitree_ros#34]
@ZKBian and Unitree team, I'm wondering if I can get some assistance with building the ROS packages for Gazebo simulation. I'm running into the following error in the screenshot below:

**cannot find -lunitree_legged_sdk**

![Screenshot from 2022-02-08 07-52-11](https://user-images.githubusercontent.com/38339/153000973-0603fd1d-d2ed-4338-88fb-5045785edb4d.png)

I've gone through all the steps in the README file as well as several of the GitHub Issues. Here is what I've done:

1. Cloned unitree_ros and unitree_ros_to_real into ~/catkin_ws/src
2. Cloned unitree_legged_sdk into my home directory ~/
3. Successfully built unitree_legged_sdk as you can see here:

![Screenshot from 2022-02-08 07-58-54](https://user-images.githubusercontent.com/38339/153001792-e5b31f38-bf2a-4d84-837d-df6c6204bd77.png)

4. Added the UNITREE_LEGGED_SDK_PATH environment variable as suggested by @Zhaiweiwei0 [here](https://github.com/unitreerobotics/unitree_ros/issues/12#issuecomment-879680139)
5. But running **catkin build** in my workspace yields the error I posted above 

Could this possibly be a ROS Noetic issue? Any help would be greatly appreciated.

Thank you.

**Comment by dbaldwin** [comment]
I was able to get this to build by changing this line:

https://github.com/unitreerobotics/unitree_ros_to_real/blob/master/unitree_legged_real/CMakeLists.txt#L24

```
string(CONCAT LEGGED_SDK_NAME libunitree_legged_sdk.so)
```

to:

```
string(CONCAT LEGGED_SDK_NAME libunitree_legged_sdk_amd64.so)
```

Since my architecture is amd64. But I'd still like to understand why the normal build process didn't work for me.

**Comment by cyoahs** [comment]
Just for future travellers:

I came across the similar issue again with latest version of `unitree_ros_to_real` and `unitree_legged_sdk`, and solved with a similar change:

from 

```
set(LEGGED_SDK_NAME -pthread libunitree_legged_sdk_${ARCH}.so lcm)

link_directories(${CMAKE_SOURCE_DIR}/unitree_legged_sdk-master/lib)
```

to

```
set(LEGGED_SDK_NAME -pthread libunitree_legged_sdk.a lcm)

link_directories(${CMAKE_SOURCE_DIR}/unitree_legged_sdk/lib/cpp/${ARCH})
```

Perhaps lcm can be removed too, because Go1 no longer depand on it.
