### ISSUE TITLE
Low level control does not update 

### ISSUE THREAD

**Issue by tahir1069** [unitreerobotics/unitree_ros#4]
The three examples provided for the ros driver in low level control does not work i.e. update motor position. For example after running position control the there should be printed the current position of the front right joint but it prints 0.0 though moving the joint also don't update. Similar is true for other two torque and velocity example. Walking example works very fine.

FYI: Similar examples in `unitree_legged_sdk` works very fine.

**Comment by ZKBian** [comment]
Hi, if the position does not update, that means the network connection between your PC and robot does not work correctly. Please check the connection with the guide in README.
