### ISSUE TITLE
How to get torso_odom in the gazebo?

### ISSUE THREAD

**Issue by skywoodsz** [unitreerobotics/unitree_ros#45]
Hi, I want to control a1 in the gazebo and need the gt odom published by the gazebo.
I know the topic of gt odom is "torso_odom". However, the topic always disappears. 
How can I fix the problem? Thanks.

**Comment by skywoodsz** [comment]
My system is ubuntu1604, ros-kinetic and gazebo8.

**Comment by xyq1223** [comment]
Hello,you can refer to this link to rerun the program.
https://github.com/unitreerobotics/unitree_guide

**Comment by skywoodsz** [comment]
> Hello,you can refer to this link to rerun the program. https://github.com/unitreerobotics/unitree_guide

Thanks! I have solved this problem!
