### ISSUE TITLE
When high level mode will be available in gazebo?

### ISSUE THREAD

**Issue by AlexKaravaev** [unitreerobotics/unitree_ros#5]
Hi, we have one of A1 robots and we need some simulation testing to run the robot. 

When the walking will be available in gazebo? If not, will it be hard to write this package by our own?

**Comment by tahir1069** [comment]
Hi if you are not looking for Gazebo specifically. We have a working example in Webots simulator. You can find the repo [here](https://github.com/MYBOTSHOP/mbs_unitree_ros). We are actively working on it so you can update as well.
Hope this helps.

**Comment by Zhaiweiwei0** [comment]
Sorry, we do not have this ROS package，this is a little difficult for beginners.

**Comment by itaouil** [comment]
Hi @edward9503  @AlexKaravaev,

Did you by any chance figure out a way to do high level control in simulation?

**Comment by AlexKaravaev** [comment]
@itaouil Hi!

Unfortunetaly no. Seems like it will require to write own control of the joints, which seems to be pretty hard
