### ISSUE TITLE
How to run on amd

### ISSUE THREAD

**Issue by elouanXP** [unitreerobotics/unitree_ros#56]
I have the error: cannot find -lunitree_legged_sdk_amd64

Can someone help me ?

**Comment by JulienRineau** [comment]
Hi, I had the same problem few days ago.
[Here](https://drive.google.com/file/d/1W7t7Y_xllz5-MHq60X3pE-XEJg6Dg9gU/view?usp=share_link) is a tutorial that might help you

**Comment by elouanXP** [comment]
Thanks
