### ISSUE TITLE
Using the Moveit of ROS to control real Z1 Manipulator

### ISSUE THREAD

**Issue by Npang-WXY** [unitreerobotics/unitree_ros#64]
Is there a function package for using ROS Moveit to control the real Z1 robot arm? If not, when will it be released?

**Comment by xyq1223** [comment]
Hello,it's already in the final stage, will give as soon as possible.

**Comment by Agnel-Wang** [comment]
The [Z1_ROS](https://github.com/unitreerobotics/z1_ros) package has been provided now.
