### ISSUE TITLE
ROS 2 Support?

### ISSUE THREAD

**Issue by SteveMacenski** [unitreerobotics/unitree_ros#7]
Hi,

I have an A1 with the expressed goal of making it work with the new and improved ROS 2 navigation2 system. Do you have drivers that work with ROS 2 foxy or any of the ROS2 distributions?

**Comment by dlee640** [comment]
Hello @SteveMacenski , it's nice to see you here (I am familiar with your work on spatio temporal voxel filter!). I have been working on this exact task recently. Please let me know if your team is working on this, or looking for someone to collaborate. Thank you.

**Comment by SteveMacenski** [comment]
I've essentially given up on it and am waiting for someone else to do it. I love the Unitree hardware, the robot itself is great, but the software support is terrible and a ton of false advertising

**Comment by ZKBian** [comment]
Hello, until now we does not work on ROS2, and does not plan to support ROS2 recently.

**Comment by MAVProxyUser** [comment]
It is unfortunate Unitree is so non-responsive to requests like this. Github is festering with questions that remain unanswered.

**Comment by MAVProxyUser** [comment]
This seems to address the question at hand? https://github.com/unitreerobotics/unitree_ros2_to_real/blob/main/ros2_unitree_legged_msgs/CMakeLists.txt

**Comment by JuloWaks** [comment]
Any updates? Is ROS2 officially supported?

**Comment by kitare17** [comment]
Is ROS2 officially supported?
