### ISSUE TITLE
How to get image ros topic

### ISSUE THREAD

**Issue by kenloumixx** [unitreerobotics/unitree_ros#71]
Hello,

I'd like to ask how A1 can obtain images from camera through ros topic.

In specific, is it possible to publish images to rostopic only with realsense-ros and additional sdk packages such as [librealsense](https://github.com/IntelRealSense/librealsense) or pyrealsense? or another Unitree-specific package is needed?

**Comment by xyq1223** [comment]
Hi, it is possible to publish images to rostopic using only realsense-ros and other sdk packages, does not require another Unitree specific package

**Comment by kenloumixx** [comment]
@xyq1223  Thank you for the response :)
