### ISSUE TITLE
better z1.urdf

### ISSUE THREAD

**Issue by siilats** [unitreerobotics/unitree_ros#73]
Hi here is a better z1.urdf exported from the latest xacro file, one in the repo is old
[z1_v2.urdf.txt](https://github.com/unitreerobotics/unitree_ros/files/11872864/z1_v2.urdf.txt)

**Comment by siilats** [comment]
xacro src/unitree_ros/robots/z1_description/xacro/robot.xacro > src/unitree_ros/robots/z1_description/xacro/z1_v2.urdf

**Comment by Agnel-Wang** [comment]
Thanks. The z1.urdf has been updated.
