### ISSUE TITLE
Ability to run user ROS code on internal A1 computer

### ISSUE THREAD

**Issue by SteveMacenski** [unitreerobotics/unitree_ros#9]
Hi,

Is it possible to run our ROS nodes on the internal computer inside of the A1 or do we require an external computer? For instance, if I wanted to run the ROS 2 navigation stack with a waypoint follower node, would that have to be done on a separate machine connected over ethernet and share the ROS network or could I add it to the robot computer? How much compute power is left on the internal computer after the system operations?

**Comment by ZKBian** [comment]
Hi, does your A1 has a NX? If so you can try to run your ROS2 node on NX. If your A1 just have a Raspberry Pi, we afraid that the power is not enough.
