### ISSUE TITLE
catkin_make error about plugin/draw_force_plugin.cc.o

### ISSUE THREAD

**Issue by abloomyt** [unitreerobotics/unitree_ros#93]
ubuntu version : 20.04
ros version : noetic
gazebo version : 11
I'm sorry to bother you. I met some problems when compiling unitree_gazebo, as shown in the picture below. Could someone please answer them for me? Thank you!
![f04226b1c7eb92d60a1cc87c0e58453a](https://github.com/unitreerobotics/unitree_ros/assets/89628987/4455518b-3168-45ec-911d-1f0df566da01)

**Comment by yiyuc** [comment]
Everything still runs if you don't compile with the plugins. When updating from melodic to noetic, some functions in the visualization part change so you can't compile with ros noetic

**Comment by abloomyt** [comment]
I reinstalled the system and the compilation passed. Thank you for your help.
